server:
  port: 7079
#server:
#  port: 8080  # Replace 8080 with your desired port number

spring:
  application:
    name=Accounts
  datasource:
    url: jdbc:mysql://localhost:3306/easy_bytes?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

