server:
  port: 7081
spring:
  application:
    name:Loans
  datasource:
    url: jdbc:mysql://localhost:3306/easy_bytes?createDatabaseIfNotExist=true
    #driver-class-name: com.mysql.cj.jdbc.driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace
